/////////////////////////////////////////////////////////////////////////////////////////////
//////DO NOT EDIT THIS FILE
////////////////////////////////////////////////////////////////////////////////////////////

package ucd.ai.cf;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Set;

/**
 * DatasetWriter is used to write Profiles back out to a file that can be read in later
 *
 */
public class DatasetWriter {

	private String dataFilename;

	/** This constructs a DatasetWriter with the given profile and movie files to write to
	 * 
	 * @param itemFile the path to the item file, e.g. "MovieLens/u.item"
	 * @param dataFile the path to the profile file, e.g. "MovieLens/u-filtered.data"
	 */
	public DatasetWriter(final String itemFile, final String dataFile) {
		this.dataFilename = dataFile;
	}

	/**
	 * This writes the given set of profiles to file.
	 * @param profiles the set containing the profiles to be written.
	 * @throws Exception
	 */
	public void writeData(final Set<Profile> profiles) throws Exception{
		BufferedWriter writer = new BufferedWriter(new FileWriter(dataFilename));
		for (Profile profile: profiles) {
			for (Rating rating: profile.getRatings()) {
				writer.write(rating.toString());
				writer.newLine();
			}
		}
		writer.close();
	}
}
